"""Add created_at field to Story

Revision ID: 4a7295e91ef5
Revises: 59c6b654dfc5
Create Date: 2023-10-26 21:58:05.511625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a7295e91ef5'
down_revision = '59c6b654dfc5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('story', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('story', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
